[server]
headless = true
address = "0.0.0.0"
port = 8501
fileWatcherType = "none"
folderWatchBlacklist = ["data", "ml", "ebpf_core", ".git", "__pycache__"]

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
